language: node_js
node_js:
  - 13

services:
  - docker

#pre-resting installs
install:
  - echo "nothing should be instslled"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t env-node --build-arg NAME=${NAME}  .
  - docker tag env-node dante9623/env-node:latest

after_success:
  - echo "dante9623" | docker login -u "dante9623" --password-stdin
  - docker push dante9623/env-node
